[data]
input_file = "/Users/baart_f/data/ais/AISVesselTracks2024_processed.parquet"

[visualization]
zoom = 10
tile_size = 1024
line_width = 1
category_column = "VesselGroup" # Column to group counts by
bbox = [-174.0, 11.0, -60.0, 51.5]  # Full extent calculated from dataing Box (EPSG:4326): MinX, MinY, MaxX, MaxY
batch_size = 20

[resources]
memory_target = 0.6
memory_spill = 0.7
memory_pause = 0.8


[style]
# Crameri Oslo (L=20% start)
colormap = "oslo"
