[project]
name = "ais-visualization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bokeh>=3.8.1",
    "click>=8.3.1",
    "colorcet>=3.1.0",
    "dask[distributed]>=2025.11.0",
    "dask-geopandas>=0.5.0",
    "datashader>=0.18.2",
    "geoviews>=1.15.0",
    "holoviews>=1.22.0",
    "hvplot>=0.12.1",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "tqdm>=4.67.1",
    "cartopy>=0.25.0",
    "rioxarray>=0.20.0",
    "morecantile>=7.0.0",
    "rio-cogeo>=7.0.0",
    "netcdf4>=1.7.3",
    "zarr>=2.18.0",
]

[project.scripts]
ais-visualization = "ais_visualization.cli:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/ais_visualization"]
